import { Profile } from "../../../autogenerated/src/grpcServer/protobuf/profile_pb";

export const profiles: { [id: string]: Profile.AsObject } = {
  "1": {
    id: 1,
    firstname: "Patrick",
    lastname: "Desjardins",
    yearactive: 15,
    friendidsList: [2, 3, 4]
  },
  "2": {
    id: 2,
    firstname: "Melodie",
    lastname: "Savaria",
    yearactive: 10,
    friendidsList: [1]
  },
  "3": {
    id: 3,
    firstname: "Alicia",
    lastname: "Desjardins",
    yearactive: 1,
    friendidsList: [1, 2]
  },
  "4": {
    id: 4,
    firstname: "Jacob",
    lastname: "Desjardins",
    yearactive: 0,
    friendidsList: [2, 3]
  },
}