# generate js codes via grpc-tools
npx grpc_tools_node_protoc \
--js_out=import_style=commonjs,binary:./autogenerated \
--grpc_out=./autogenerated \
./src/grpcServer/protobuf/*.proto

# generate d.ts codes
npx protoc-bin \
--ts_out=./autogenerated/src/grpcServer/protobuf \
--proto_path=./src/grpcServer/protobuf \
./src/grpcServer/protobuf/*.proto