# generate js codes via grpc-tools
grpc_tools_node_protoc \
--js_out=import_style=commonjs,binary:../autogenerated \
--grpc_out=./autogenerated \
--plugin=protoc-gen-grpc=`which grpc_tools_node_protoc_plugin` \
-I ./proto \
../src/grpcServer/protobuf/*.proto

# generate d.ts codes
protoc \
--plugin=protoc-gen-ts=./node_modules/.bin/protoc-gen-ts \
--ts_out=./autogenerated \
-I ./proto \
../src/grpcServer/protobuf/*.proto