import { Profile as GrpcProfile } from "../../../autogenerated/src/grpcServer/protobuf/profile_pb";
import { Profile } from "../../../generated/graphql/types";

export class ProfileMapper {
    public static mapGrpcProfileToGraphQLProfile(grpcProfile: GrpcProfile | undefined): Profile {
        if (grpcProfile === undefined) {
            return { id: -1, name: "" };
        }
        return { id: grpcProfile.getId(), name: `${grpcProfile.getFirstname()} ${grpcProfile.getLastname()}` };
    }
}
